name: "Workflow Lint"

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  merge_group:
    types: [ checks_requested ]

permissions:
  contents: read

jobs:
  zizmor:
    name: Check workflow permissions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
          annotations: true
          min-severity: low
